/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    List: typeof import('./components/Timeline/suggest/showcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSlot: typeof import('./components/SearchSlot.vue')['default']
    ShopInfo: typeof import('./components/Shop/ShopInfo.vue')['default']
    ShopsList: typeof import('./copmponents/Shops/ShopsList.vue')['default']
    Showcase: typeof import('./components/Suggest/showcase.vue')['default']
    Suggest: typeof import('./components/Suggest/index.vue')['default']
    Timeline: typeof import('./components/Timeline/suggest/index.vue')['default']
  }
}
