services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      APP_ADDR: :8080
      NS_MARIADB_USER: root
      NS_MARIADB_PASSWORD: pass
      NS_MARIADB_HOSTNAME: db
      NS_MARIADB_PORT: "3306"
      NS_MARIADB_DATABASE: app
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

  caddy:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - server
      - client

  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: mysql --user=root --password=pass --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 30

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
