name: Server CI

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./server/go.mod
          cache-dependency-path: ./server/go.sum
      - name: Build with xc
        run: go run github.com/joerdav/xc/cmd/xc@latest build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./server/go.mod
          cache-dependency-path: ./server/go.sum
      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=10m
          working-directory: ./server

  #  test-unit:
  #    name: Unit Test
  #    runs-on: ubuntu-latest
  #    defaults:
  #      run:
  #        working-directory: ./server
  #    needs:
  #      - build
  #    steps:
  #      - uses: actions/checkout@v4
  #      - uses: actions/setup-go@v5
  #        with:
  #          go-version-file: ./server/go.mod
  #      - name: Unit test with xc
  #        run: go run github.com/joerdav/xc/cmd/xc@latest test-unit
  #
  #  test-integration:
  #    name: Integration Test
  #    runs-on: ubuntu-latest
  #    defaults:
  #      run:
  #        working-directory: ./server
  #    needs:
  #      - build
  #    steps:
  #      - uses: actions/checkout@v4
  #      - uses: actions/setup-go@v5
  #        with:
  #          go-version-file: ./server/go.mod
  #      - name: Integration test with xc
  #        run: go run github.com/joerdav/xc/cmd/xc@latest test-integration

  dependabot-automerge:
    name: Dependabot Automerge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs:
      - build
      - lint
    #      - test-unit
    #      - test-integration
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2
        id: metadata
      - uses: actions/checkout@v4
      - name: Enable automerge
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr merge ${{ github.event.number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
